#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose
main([Arg]) ->
    case Arg of
        "html" ->
            {ok, ErlangFiles} = file:list_dir("./erlang"),
            NewErlangFiles = ["./erlang/" ++ File || File <- ErlangFiles],
            {ok, NovaFiles} = file:list_dir("./nova"),
            NewNovaFiles = ["./nova/" ++ File || File <- NovaFiles],
            {ok, BeamFiles} = file:list_dir("./otherbeamlang"),
            NewBeamFiles = ["./otherbeamlang/" ++ File || File <- BeamFiles],
            MergedList = NewNovaFiles ++ NewErlangFiles ++ NewBeamFiles,
            JoinedString = string:join(MergedList, " "),
            Result = output_html(JoinedString),
            io:format("~p~n", [Result]);
        Arg ->
            io:format("Arg ~p not supported~n", [Arg])
    end.

output_html(Files) ->
    os:cmd("pandoc --toc " ++ Files ++ " -f markdown -t html  -s -o output/novabook.html --highlight-style tango").